var giusta = [
/*0*/	"0",
/*1*/	"75",
/*2*/	"800 million",
/*3*/	"Saint Patrick, Saint George, Saint Andrew",
/*4*/	"The Welsh dragon",
/*5*/	"Windsor",
/*6*/	"From Lord Sandwich, a British nobleman",
/*7*/	"Oscar Wilde",
/*8*/	"London", 
/*9*/	"Mountain of light",
/*10*/	"In Denmark",
/*11*/	"Christmas Pudding",
/*12*/	"Robert Louis Stevenson",
/*13*/	"A doctor who created a monster",
/*14*/	"Oats",
/*15*/	"Oliver Twist",
/*16*/	"A panoramic wheel",
/*17*/	"The Shard is 310m high",
/*18*/	"The Olympic games", 
/*19*/	"13 horizontal stripes",
/*20*/	"The original thirteen colonies",
/*21*/	"50",
/*22*/	"The number of states in the USA", 
/*23*/	"He was born in Honolulu, Hawaii",
/*24*/	"Washington DC",
/*25*/	"Albany",
/*26*/	"Sacramento",
/*27*/	"From the Dachsumund, a small long dog",
/*28*/	"A Malasyan sauce made from fish",
/*29*/	"From the name of Bikini atoll",
/*30*/	"A maple leaf",
/*31*/	"- 50 degrees C",
/*32*/	"Celine Dion; Avril Lavigne",
/*33*/	"The Union Jack",
/*34*/	"The constellation of the Southern Cross",
/*35*/	"Because it is under the Equator",
/*36*/	"Eucalyptus",
/*37*/	"The All Blacks",
/*38*/	"The kiwi",
/*39*/	"Larvae of beetles",
/*40*/	"From a brand of canned chopped meat",
];